[package]
name = "ship"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
semver_rs = "0.2"
serde = { version = "1.0", features = ["derive"] }
git2 = "0.13"
regex = "1.5.4"
